(maint) Add gha workflow test for noarch artifacts package installs

diff --git a/.github/workflows/pr_testing_install_build_artifact.yaml b/.github/workflows/pr_testing_install_build_artifact.yaml
--- a/.github/workflows/pr_testing_install_build_artifact.yaml
+++ b/.github/workflows/pr_testing_install_build_artifact.yaml
@@ -72,3 +72,64 @@ jobs:
           PT__installdir: ${{ github.workspace }}
           PT_version: "8.15.0"
         run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh
+
+  test-install-build-artifact-task-noarch:
+    strategy:
+      matrix:
+        details:
+          - image: almalinux:9
+            prereqs:
+              - java-17-openjdk-headless
+              - net-tools
+              - procps-ng
+              - which
+          - image: debian:12
+            prereqs:
+              - openjdk-17-jre-headless
+              - net-tools
+              - procps
+          - image: ubuntu:24.04
+            prereqs:
+              - openjdk-17-jre-headless
+              - net-tools
+              - procps
+    runs-on: ubuntu-latest
+    container: ${{ matrix.details.image }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          path: openvox_bootstrap
+      - id: prep
+        uses: ./openvox_bootstrap/.github/actions/container_task_prep
+      - name: Run openvox-agent install task manually
+        env:
+          PT__installdir: ${{ github.workspace }}
+          PT_version: "8.19.1"
+        run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh
+      - name: Install prerequisites
+        shell: bash
+        env:
+          PREREQ_PACKAGES: ${{ join(matrix.details.prereqs, ',') }}
+        run: |-
+          set +e
+          /opt/puppetlabs/bin/puppet apply --detailed-exitcodes <<EOS
+          package { [${PREREQ_PACKAGES}]:
+            ensure => installed
+          }
+          EOS
+          exitcode=$?
+          set -e
+          # Expect package changes and no failures.
+          [[ "${exitcode}" -eq 2 ]]
+      - name: Test noarch package installation
+        env:
+          PT__installdir: ${{ github.workspace }}
+          PT_package: "openvox-server"
+          PT_version: "8.8.0"
+        run: ./openvox_bootstrap/tasks/install_build_artifact_linux.sh
+      - name: Verify openvox-server is installed
+        shell: bash
+        run: |-
+          /opt/puppetlabs/bin/puppet resource package openvox-server > openvox-server.status
+          cat openvox-server.status
+          grep "ensure.*=>.*'8.8.0" openvox-server.status
