Add a step to validate the check task
Adds a very basic acceptance test for the check task to verify that it
would in fact raise an error for a failed version test. Does not test
the version checking exhaustively, or the behavior of check_linux.sh
when package is missing. Could come back to that.

diff --git a/.github/workflows/pr_testing.yaml b/.github/workflows/pr_testing.yaml
--- a/.github/workflows/pr_testing.yaml
+++ b/.github/workflows/pr_testing.yaml
@@ -45,6 +45,14 @@ jobs:
         run: bolt task run openvox_bootstrap::check --targets localhost --run-as root
       - name: Verify idempotency
         run: bolt task run openvox_bootstrap::install --targets localhost --run-as root
+      - name: Verify that check task can provide a negative result
+        run: |-
+          if bolt task run openvox_bootstrap::check --targets localhost --run-as root version=8 test=lt; then
+            echo "Check task should have failed version test but did not"
+            exit 1
+          else
+            echo "Check task correctly failed version test"
+          fi
 
   test-install-task-on-other-os-via-containers:
     strategy:
